### ISSUE TITLE
重排标题

### ISSUE THREAD

**Issue by postyizhan** [postyizhan/NitWikit#175]
https://github.com/postyizhan/NitWikit/issues/84

文档不能使用（不渲染）一级标题，这使得文档中有些目录看起来很奇怪

我们需要将部分原一级标题改为二级标题，原二级标题改为三级标题等，通常每个 md 只需要保留一个一级标题

同时我在想，每一个 md 是否需要一个根节点？

![图片](https://github.com/user-attachments/assets/f56a6c5f-fd9f-472e-a1db-aa85e9612db1)

如果一级标题可以渲染的话，图中的二级标题都会在一级标题之下，我想这会让目录结构更加清晰

下方是我发现需要更改的标题（有待补充）：

#### doc
| 地址 | 是否完成 |
| --- | --- |
| https://github.com/postyizhan/NitWikit/main/docs/advance/database/configure.md | ❌ |
| https://yizhan.wiki/NitWikit/database | ❌ |
| https://github.com/postyizhan/NitWikit/main/docs/advance/database/uninstall.md | ❌ |
| https://github.com/postyizhan/NitWikit/main/docs/preparation/text-editor.md | ❌ |
| https://github.com/postyizhan/NitWikit/blob/main/docs/start/basic/what-is-server.md | ❌ |

#### doc-java
| 地址 | 是否完成 |
| --- | --- |
| https://github.com/postyizhan/NitWikit/main/docs-java/preparation/websites.md | ❌ |
| https://github.com/postyizhan/NitWikit/tree/main/docs-java/process/maintenance/anticheat | ❌ |
| https://yizhan.wiki/NitWikit/Java/cross-server | ❌ |
| https://yizhan.wiki/NitWikit/Java/advance/cross-server/plugin/BC&WF | ❌ |
| https://yizhan.wiki/NitWikit/Java/advance/cross-server/plugin/velocity | ❌ |
| https://yizhan.wiki/NitWikit/Java/advance/Resource-pack-distribution | ❌ |
| https://yizhan.wiki/NitWikit/Java/preparation/websites | ❌ |

#### doc-bedrock
| 地址 | 是否完成 |
| --- | --- |

**Comment by postyizhan** [comment]
![图片](https://github.com/user-attachments/assets/c407a9a6-b441-4ea0-aeb4-74a1c43bfb04)
![图片](https://github.com/user-attachments/assets/4ea17029-bb9e-4844-9517-900fdc38b815)
应该统一只写文件名或者都加上汉化两字

**Comment by postyizhan** [comment]
https://yizhan.wiki/NitWikit/Java/advance/loginchoices
![图片](https://github.com/user-attachments/assets/29e06c04-0367-46b7-a668-88148c7cbfcc)
不要冒号

**Comment by Yaosanqi137** [comment]
数据库那边的标题我按要求排版了
#196

**Comment by postyizhan** [comment]
https://github.com/postyizhan/NitWikit/pull/290
