### ISSUE TITLE
删除文档右上角语言选项

### ISSUE THREAD

**Issue by postyizhan** [postyizhan/NitWikit#188]
![图片](https://github.com/user-attachments/assets/dc09ce49-d6aa-48d3-a3d1-a5aae47ab6ad)

**Comment by MengHanLOVE1027** [comment]
稍等，我来♂~~~~

**Comment by MengHanLOVE1027** [comment]
# 引用
![image](https://github.com/user-attachments/assets/81d939b2-9692-4458-83e8-dfffe8494a22)
# 这个在官网文档里面是有讲到的，直接注释即可
![image](https://github.com/user-attachments/assets/4c972eec-5473-46ed-98e9-a792f62a0c0e)
# 效果：
![image](https://github.com/user-attachments/assets/44a35e1b-1af4-493e-bec3-2b5fadf33a68)

**Comment by MengHanLOVE1027** [comment]
稍后进行pr

**Comment by MengHanLOVE1027** [comment]
见此PR: https://github.com/postyizhan/NitWikit/pull/192

**Comment by postyizhan** [comment]
https://github.com/postyizhan/NitWikit/pull/192
