### ISSUE TITLE
[建议] 统一一下使用的 DNS 服务商 & 另外建议"申请域名"页拆分或改名为"域名与DNS配置"

### ISSUE THREAD

**Issue by Lafcadia** [postyizhan/NitWikit#214]
以 [申请域名](https://yizhan.wiki/NitWikit/advance/apply-for-a-domain-name/) 为例。

前半部分以阿里云、万网为主要的例子，而 `DDNS 服务` 中则以腾讯云为主要示例。可能会造成混淆。

**Comment by Lafcadia** [comment]
> 以 [申请域名](https://yizhan.wiki/NitWikit/advance/apply-for-a-domain-name/) 为例。
> 
> 前半部分以阿里云、万网为主要的例子，而 `DDNS 服务` 中则以腾讯云为主要示例。可能会造成混淆。

除此之外，申请域名页的大部分内容都是 DNS 配置，可能并不是 `申请域名` 可以概括的。

**Comment by postyizhan** [comment]
那怎么办

**Comment by Lafcadia** [comment]
好像这个已经早就该Close了
