### ISSUE TITLE
建议在逗号后添加空格

### ISSUE THREAD

**Issue by MrXiaoM** [postyizhan/NitWikit#273]
如你所见，[`40abdba`](https://github.com/postyizhan/NitWikit/commit/40abdba6222aebaa023df7eefb09bf4f751a1e5a) 将所有的中文逗号改成了英文逗号，如果实在要求全部使用英文逗号，建议在其后方添加一个空格以增强可读性。

**Comment by postyizhan** [comment]
本来用英文逗号的，后来写了文档规范，我还把所有英文逗号换成中文逗号，结果llf都不说一下，自己又换回去了

**Comment by postyizhan** [comment]
统一使用中文逗号，不同意的踹出仓库
![209df0fad39954f056738868580852ad](https://github.com/user-attachments/assets/e65f7b7b-e351-4f7d-ab29-67cb49153603)

**Comment by postyizhan** [comment]
回退了 https://github.com/postyizhan/NitWikit/pull/281
