### ISSUE TITLE
优化误区被吃了？

### ISSUE THREAD

**Issue by gyc123456-1** [postyizhan/NitWikit#28]
![image](https://github.com/postyizhan/NitWikit/assets/69791212/6ea7091b-96c9-4884-848b-da80dde77106)
这个绿色链接404啊

**Comment by lilingfengdev** [comment]
改成优化插件了，你可以更新一下

**Comment by postyizhan** [comment]
已更改 https://github.com/postyizhan/NitWikit/commit/d57035b5bca0e523b3847153dea3a62242107ad4

另外我打算编写文档的书写规范，不知您能否给些建议？

**Comment by gyc123456-1** [comment]
> 已更改 [d57035b](https://github.com/postyizhan/NitWikit/commit/d57035b5bca0e523b3847153dea3a62242107ad4)
> 
> 另外我打算编写文档的书写规范，不知您能否给些建议？

建议搞个书写规范放仓库wiki里，readme里搞个链接
下面只做个目前编辑建议
1. 英语前后添加空格
2. 标点符号统一改成全角（特殊地方除外）
3. 改下一些格式用的不合理的地方，比如**bold**用成`code`的
4. 修正警告等级（danger，warning，info，tip什么的），应该搞个标准判断下信息重要程度
5. 使用[标准化译名](https://zh.minecraft.wiki/w/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96)
6. 配置文件不要纯机翻，最好人工审查一遍
7. 插件/网站的拼写最好以网页内为准

另外，多语言如果不行的话还是把语言切换删了吧
