### ISSUE TITLE
全核心介绍

### ISSUE THREAD

**Issue by postyizhan** [postyizhan/NitWikit#292]
介绍mc服务器从诞生到现在曾出现过的有名有姓的服务端核心

来源，结果，是否还在维护，以及对圈子的贡献

**Comment by HanSiqi2008** [comment]
wow，那我是不是可以挂个SpongeForge上去（bushi）

**Comment by lilingfengdev** [comment]
个人感觉没必要,首先就是工作量非常大,其次就是真的没有人去看，顶天介绍，一些有点名气还在更新就够了

**Comment by minimouse0** [comment]
写一篇简短文章应该就行，“最开始为了自定义服务器，有人开发出了a，后来为了xxx，a上发展出了b分支，随后为了xxx又发展了出c分支，a分支因为xxx原因终止支持，e核心因内部原因又有了f核心”

**Comment by postyizhan** [comment]
https://github.com/postyizhan/NitWikit/commit/8f1209b47557f7c397381e7bee687e6526da3725
