### ISSUE TITLE
构建插件

### ISSUE THREAD

**Issue by postyizhan** [postyizhan/NitWikit#296]
IDEA：https://docs.superiormc.cn/new-user-doc/fu-zhu-ye-yao-hui-yi-dian-zhe-xie/4.1-kai-yuan-cha-jian-de-gou-jian

我们把这个贴上去，再写个命令行的

**Comment by Radiation-pi** [comment]
建议写一下 action 怎么操作，很多插件都建议 fork 了直接 action 跑

**Comment by Dreeam-qwq** [comment]
如果真要写，建议附上，如有能力推荐购买插件支持作者，类似的话(

**Comment by postyizhan** [comment]
https://github.com/postyizhan/NitWikit/commit/c0ada523a1be7fe29dd1dcc7a1a180cc250876c7
