### ISSUE TITLE
是否有拟定贡献流程？

### ISSUE THREAD

**Issue by alex3236** [postyizhan/NitWikit#49]
贵项目是否有计划编写生电部分的内容？如果可以，我想试试编写这部分内容（

**Comment by Radiation-pi** [comment]
笨蛋文档是给笨蛋开服写的，生电是指的教生电还是教如何开生电服呢，如果是后者的话我认为是可以的

**Comment by Radiation-pi** [comment]
至于你说的贡献流程，我们前期基本上就是朋友互相介绍，大概拟定一下板块然后找自己擅长的地方 commit 就好，不过不得不说笨蛋文档里大多数都是bukkit的东西，fabric的东西可能不是很多（我们也不是很了解），所以可能写的话你可以写成拓展阅读？当然，如果你讲讲bukkit 生电开服啥的也是可以的（比如leaves把paper的什么特性修了）

更多的话，我建议可以在文档 intro 部分的 qq 群里交流一下，文档主维护者是住校生所以可能我们需要进一步交流一下？您看方便吗？

**Comment by Radiation-pi** [comment]
readme主要贡献者里都可以联系的嗷（但是lilingfeng和yizhan工作日出现的比较少一些），建议先加加群讨论一下ovo

611076407

**Comment by lilingfengdev** [comment]
生电内容当然可以，我个人也有此类计划，既然这位大佬想写，那就辛苦你了,如果可以的话，我会考虑写一个一键脚本，开启插件端生电模式
