### ISSUE TITLE
关于开服中途修改为正版验证的解决方案

### ISSUE THREAD

**Issue by yfy-dodo939** [postyizhan/NitWikit#67]
在 Wiki 的 [/正式开服/开启服务端#正版验证](https://nitwikit.yizhan.wiki/%E6%AD%A3%E5%BC%8F%E5%BC%80%E6%9C%8D/%E5%BC%80%E5%90%AF%E6%9C%8D%E5%8A%A1%E7%AB%AF#%E6%AD%A3%E7%89%88%E9%AA%8C%E8%AF%81) 部分提到了 **“不要开服开到一半去改正版验证! 这会造成UUID混乱，玩家数据丢失”** ，针对这个问题，**[此项目](https://github.com/yfy-dodo939/Offline2OnlineUUIDFix)** 通过查询 uuid 并修改对应文件名或者文件内容解决了从离线到正版服务器的玩家数据转换问题，或许会对部分服主有所帮助。

项目地址: https://github.com/yfy-dodo939/Offline2OnlineUUIDFix

**Comment by postyizhan** [comment]
https://github.com/postyizhan/NitWikit/commit/368f3706f9ba1bd9c490c2152e9a2ae31039fd7b
