### ISSUE TITLE
不渲染一级标题

### ISSUE THREAD

**Issue by postyizhan** [postyizhan/NitWikit#84]
![图片](https://github.com/postyizhan/NitWikit/assets/97342038/2d561788-3554-4b15-955c-2efbd2e8aaf2)

**Comment by Lafcadia** [comment]
能给一下源代码位置吗（（（找都找不到

**Comment by postyizhan** [comment]
> 能给一下源代码位置吗（（（找都找不到

指这个md文件的位置？

**Comment by Lafcadia** [comment]
> > 能给一下源代码位置吗（（（找都找不到
> 
> 指这个md文件的位置？

yes.

**Comment by postyizhan** [comment]
> > > 能给一下源代码位置吗（（（找都找不到
> > 
> > 
> > 指这个md文件的位置？
> 
> yes.

https://yizhan.wiki/NitWikit/maintenance/anticheat/anticheatplugins

**Comment by liangcha385** [comment]
> https://yizhan.wiki/NitWikit/maintenance/anticheat/anticheatplugins

链接已更改为 https://yizhan.wiki/NitWikit/process/maintenance/anticheat/anticheatplugins
_跟 [#118](https://github.com/postyizhan/NitWikit/pull/118) 有的一拼_

**Comment by liangcha385** [comment]
**如果你对这个问题比较较真的话**

文档有许多地方都出现 只渲染一级标题与二级标题而不渲染三级标题 或者 只渲染二级标题与三级标题而不渲染三级标题 的情况
只不过其中有部分会觉得很合理或者压根没多少人在意而导致被忽略

例子有这些
https://yizhan.wiki/NitWikit/process/maintenance/how-to-defend-against-cyber-attacks
https://yizhan.wiki/NitWikit/process/maintenance/anticheat/antixray
https://yizhan.wiki/NitWikit/process/maintenance/anticheat/rng
https://yizhan.wiki/NitWikit/process/maintenance/backup
https://yizhan.wiki/NitWikit/process/maintenance/how-to-troubleshoot-problematic-plugins

_还有一大坨这里不方便放出_

**Comment by lilingfengdev** [comment]
既然没人能解决，那就没必要留着了

**Comment by TheFloodDragon** [comment]
https://docusaurus.io/docs/markdown-features/toc#table-of-contents-heading-level
